version: '3'

services:
  machine:
#    image: appdynamics/machine:4.4
    env_file:
     - appdynamics.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock