version: '3'

services:
  machine:
#    image: appdynamics/machine:4.4
    environment:
     - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
#     - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
     - APPDYNAMICS_CONTROLLER_HOST_NAME=10.196.160.151
     - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
     - APPDYNAMICS_CONTROLLER_PORT=8090
     - MACHINE_AGENT_PROPERTIES=-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=true
     - EXTENSIONS_CONFIGPROPFILE=/opt/appdynamics/monitors/ApacheMonitor/apache-props.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/Muddam/AppDynamics/CI/apache-monitoring-extension-ci/apache-props.env:/opt/appdynamics/monitors/ApacheMonitor/apache-props.env

  apache:
    build:
      context: .
      dockerfile: Dockerfile_Apache
    hostname: apache.fwdproxy
    ports:
        - "8585:80"