package ApacheMonitoringExtensionCi.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'e328aabe-302c-4bbc-9bf8-d3f50abb946a' (id = 'ApacheMonitoringExtensionCi')
accordingly and delete the patch script.
*/
changeProject("e328aabe-302c-4bbc-9bf8-d3f50abb946a") {
    check(archived == false) {
        "Unexpected archived: '$archived'"
    }
    archived = true
}
