package EXT_ApacheMonitoringExtensionCi.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteProject

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the project with uuid = '0da77633-ff02-4f36-9012-ecaee877a2d5' (id = 'EXT_ApacheMonitoringExtensionCi')
from your code and delete the patch script.
*/
deleteProject("0da77633-ff02-4f36-9012-ecaee877a2d5")

