package EXT_ApacheMonitoringExtension.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteBuildType

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = '679d19d3-836c-45f6-bf83-226938e45c9a' (id = 'EXT_ApacheMonitoringExtension_Build')
from your code and delete the patch script.
*/
deleteBuildType("679d19d3-836c-45f6-bf83-226938e45c9a")

