package EXT_ApacheMonitoringExtension.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteBuildType

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = '8ae04611-4cb4-4e71-97ac-95570f17f4b1' (id = 'EXT_ApacheMonitoringExtension_Build')
from your code and delete the patch script.
*/
deleteBuildType("8ae04611-4cb4-4e71-97ac-95570f17f4b1")

