package EXT_ApacheMonitoringExtension.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the vcsRoot with uuid = '7aedf499-2e1e-40f5-bc11-27ff905161ba' (id = 'EXT_ApacheMonitoringExtension_HttpsGithubComSatishMApacheMonitoringExtensionCiRe')
from your code and delete the patch script.
*/
deleteVcsRoot("7aedf499-2e1e-40f5-bc11-27ff905161ba")

