package ApacheMonitoringExtensionCi.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '0bfdf68e-6ef0-4254-b5d9-9fc4217fd772' (id = 'ApacheMonitoringExtensionCi_Compile_Test_Java7')
accordingly and delete the patch script.
*/
changeBuildType("0bfdf68e-6ef0-4254-b5d9-9fc4217fd772") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
