package ApacheMonitoringExtensionCi.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '666959DC-1804-497B-BA2B-9F94D48184E7' (id = 'ApacheMonitoringExtensionCi_Compile_Test_Java8')
accordingly and delete the patch script.
*/
changeBuildType("666959DC-1804-497B-BA2B-9F94D48184E7") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
